[workspace]
members = ["image-fetch"]
default-members = ["image-fetch"]
resolver = "1"
package.version = "0.3.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
