name: Build for aarch64-unknown-linux-gnu

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build with cross
      uses: houseabsolute/actions-cross@v1
      with:
        command: build
        args: --release --target aarch64-unknown-linux-gnu
        targets: aarch64-unknown-linux-gnu
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-binary
        path: target/aarch64-unknown-linux-gnu/release/
